mabhyHs/Henrys-app

- api/src/models/Burger.js
- api/src/models/Combo.js
> add burger model. add combo model

- client/src/Redux/store/store.js
> feat(redux/store): config store.js

- client/src/index.js
> feat(src): config index.js

- client/src/Redux/store/store.js
- client/src/index.js
> hotfix EsLint

- api/src/controllers/fries.controllers.js
- api/src/repositories/fries.repositories.js
- api/src/routes/fries.routes.js
- api/src/routes/index.js
> feat(/fries): add endpoint POST/fries

- client/src/Redux/actions/actions.js
> creacion de actions

- client/src/Redux/reducer/reducer.js
> Empiezo con los reducers

- client/src/Redux/actions/actions.js
> Correccion de errores

- client/src/Redux/store/store.js
> create(redux/store): create store

- client/src/App.js
- client/src/Components/NavBar/NavBar.css
- client/src/Components/NavBar/NavBar.jsx
- client/src/index.css
- client/src/index.js
Se crea navbar con:
- Logo que redirecciona a Home.
- Links Home, Menu, Nosotros, Contacto.
- Link de carrito.
- Dropdown para inciar sesión que muestra opciones de: Iniciar Sesión y Registrarse.
- Totalmente responsive.
Se modificaron los siguientes archivos:
**App.js:**
- Se agregó importación de Router y routes de React.
- Se eliminó la configuración del componente por defecto y se agregó componente Routes y Route.
**Index.js**
- Se agrega importación de BrowserRouter y se añadió al render.
**Index.css**
- Se agregó variable global de color para los Hovers
Faltan Funcionalidades de rutas que se va a ir agregando a medida que se vayan sumando los distintos componentes.
> Crate(Navbar component UI)

- client/src/App.js
- client/src/Components/MainHome/MainHome.css
- client/src/Components/MainHome/MainHome.jsx
Visualización del componente MainHome
> Agregado el componente MainHome

- client/src/App.js
- client/src/Components/Footer/Footer.css
- client/src/Components/Footer/Footer.jsx
Creación de UI de footer
Completamente Resposive
Falta la Funcionalidad de los Links y el form de Newsletter @NicoPavon @FLeiras @KevinZea
> Create(component footer UI)

- client/src/Components/NavBar/NavBar.css
- client/src/Components/NavBar/NavBar.jsx
Se modificó la navbar a sticky para que quede siempre en la parte superior de la app
> Refactor(NavComponent-UI)

- client/src/App.js
- client/src/Components/CardProductMenu/CardProductMenu.css
- client/src/Components/CardProductMenu/CardProductMenu.jsx
- client/src/Components/ContactForm/ContactForm.css
- client/src/Components/ContactForm/ContactoForm.jsx
- client/src/Components/Home/Home.jsx
- client/src/Components/MainHome/MainHome.jsx
- client/src/Components/Menu/Menu.css
- client/src/Components/Menu/Menu.jsx
- client/src/Components/ProductsContainerMenu/ProductsContainerMenu.jsx
Creación de la card del Menú:
- Imagen referente al producto.
- Titulo
- Botón ver mas que te lleva a detalle del producto.
- precio
- botón para agregar al carrito
Se modificaron los siguientes archivos:
**App.js**
- Se agrega la ruta de Home, Menú y Contact form
- Se importaron dichos componentes
- MainHome-- modifiqué modo de exportación.
- CardProductMenu -- Cree el componente nuevo entero UI falta la logica.
- ProductsContainerMenu -- Cree el componente importé la Card de products.
- Menu -- Cree el componente e importé ProductsContainerMenu.
- Contacto -- Cree componente de prueba.
**![Captura de pantalla (108)](https://user-images.githubusercontent.com/6260385/180497110-89769461-2a2b-471e-b772-576b41df2dc9.png)**
> Create(Card Menu and some modified files)

- client/src/Components/SearchBar/SearchBar.jsx
creado el componente SearchBar, falta el reducer!
> crear componente SearchBar

- client/src/Redux/actions/actions.js
- client/src/Redux/reducer/reducer.js
> reducers basicos listos

- client/src/Components/ContactForm/ContactoForm.jsx
creado el contactform, sin submit de momento
> Create contact form

- client/src/Components/FiltersMenu/FiltersMenu.css
- client/src/Components/FiltersMenu/FiltersMenu.jsx
- client/src/Components/Menu/Menu.jsx
- Se creó la vista de los filtros en el componente menú
- Se agregó botón para Crear Hamburguesa
- Selects para ordenamiento de mayor a menor precio
- Totalmente responsivo
Se modificaron los archivos:
- Menú
- Filters Menú
- FiltersMenu.css
> Create(UI-Filters and Order Menu)

- api/src/middlewares/beverageValidation.js
- api/src/middlewares/burgerValidation.js
- api/src/middlewares/comboValidation.js
- api/src/middlewares/friesValidation.js
- api/src/middlewares/ingredientValidation.js
- api/src/models/Fries.js
- api/src/repositories/beverage.repositories.js
- api/src/repositories/burger.repositories.js
- api/src/repositories/combo.repositories.js
- api/src/repositories/fries.repositories.js
- api/src/repositories/ingredient.repositories.js
- api/src/routes/beverage.routes.js
- api/src/routes/combo.routes.js
- api/src/routes/fries.routes.js
- api/src/routes/ingredient.routes.js
- api/src/server/express.js
algunas validaciones. Por favor revisar, y avisar si se les ocurre validar algo más.
> add POST validations. routes /beverages, /burgers, /fries, /ingredients

- client/src/Components/AboutUs/AboutUs.css
- client/src/Components/AboutUs/AboutUs.jsx
- client/src/Components/ContactForm/ContactForm.css
- client/src/Components/ContactForm/ContactoForm.jsx
Refactoricé detalles en las imágenes del Form de contacto y la sección AboutUs
> Refactoring(AboutUs and ContactForm)

- client/src/App.js
Refactoricé y agregué la ruta por defecto en caso de no encontrarse lo que se busca
> Refactor(NotFound)

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/Components/NavBar/NavBar.jsx
- client/src/Components/UserLogin/UserLogin.css
- client/src/Components/UserLogin/UserLogin.jsx
- client/src/Components/UserRegister/UserRegister.css
- client/src/Components/UserRegister/UserRegister.jsx
Se crean los componentes de registro y Login de Usuario, tiene la opción de ingresar o registrarse con google
> UI login register component

- client/src/Components/ProductsContainerMenu/ProductsContainerMenu.css
- client/src/Components/ProductsContainerMenu/ProductsContainerMenu.jsx
Se agrega estilo al contenedor de las cards en menú para conseguir que se vean de a 9 cards y rea fullresponsive
> se agrega estilo para el grid de cards en Menu

- client/src/Components/AddBurger/AddBurger.jsx
Se agrego funcionalidad de precio y botones de cantidad mas y menos y corrección de orden de ingredientes al cambiarlos de cantidad
> componente  terminado en funcionalidad

- client/src/App.js
- client/src/Components/UserPersonalInfo/UserPersonalInfo.css
- client/src/Components/UserPersonalInfo/UserPersonalInfo.jsx
Se realiza componente para mostrar los datos personales del usuario y posibilidad de editarlos.
**@FLeiras Fede fijate si así te parece, la idea es que cuando presionen sobre mis datos los lleve a este form con los datos precargados y tengan la posibilidad de editarlos, no sé si así está bien o es preferible hacerlo como campos editables, es decir que en cada campo (Nombre, apellido, mail) tenga un lápiz y sólo te habilite el campo que querés editar.**
> Create(User personal info)

- client/src/App.js
- client/src/Components/UserFavorites/UserFavorites.css
- client/src/Components/UserFavorites/UserFavorites.jsx
- client/src/Components/UserFavoritesCard/UserFavoritesCard.css
- client/src/Components/UserFavoritesCard/UserFavoritesCard.jsx
Creación del componente mis favoritos
> Create(Mis Favoritos)

- api/src/repositories/combo.repositories.js
- api/src/repositories/precharge.repositories.js
- api/src/utils/addDataDB.js
> fix precharge. fix associations. fix id violations

- client/src/App.js
- client/src/Components/UserProfileDashboard/UserProfile.css
- client/src/Components/UserProfileDashboard/UserProfile.jsx
maquetado de la dashboard de usuario
> Creado el componente userprofiledashboard

- client/src/App.js
- client/src/Components/ProductDetail/ProductDetail.jsx
- client/src/Redux/actions/actions.js
- client/src/Redux/reducer/reducer.js
El componente detalleProducto recibe un id por url y despacha una accion nueva en 'actions' y consume la api directamente de heroku y se visualiza en la pagina
Nota: falta de parte del back team que se pueda consumir de la api los ingredientes de cada producto
> Detalle de producto consumiendo api

- client/package-lock.json
- client/package.json
- client/src/Components/ContactForm/ContactoForm.jsx
Lógica y configuración del contactform con emailjs.
> config emailjs contactform

- client/src/App.js
- client/src/Components/User/UserReview/UserReview.css
- client/src/Components/User/UserReview/UserReview.jsx
- client/src/Redux/actions/actions.js
Funcionalidad y estilo
se agrego una puntuación con estrellas con valores de 1 a 5
una sección de comentarios
validación que no se pueda enviar sino hay una puntuación
una acción tipo post  que recibe la calificación y el comentario simulando que hay una ruta post
Nota: queda pendiente en el back una ruta post que reciba los datos enviados y se almacenen en la base de datos
> Creacion de componente de calificacion

- client/src/Components/AddBurger/AddBurger.css
- client/src/Components/AddBurger/AddBurger.jsx
Estilos para la creacion de hamburguesas.
> estilada la creacion de hamburguesas

- client/src/Components/ContactForm/ContactoForm.jsx
corregido error de formulario, ahora redirige al home.
> fix(contactoForm)

- client/src/Components/NavBar/NavBar.jsx
- client/src/Components/User/UserLoggedIn/UserLoggedInDropdown.css
- client/src/Components/User/UserLoggedIn/UserLoggedInDropdown.jsx
Se crea un subcomponente "UserLoggedIn" que va a aparecer cuando el usuario se encuentra logueado, en el button se va a renderizar el nombre del usuario y en el dropdown cambian las opciones por mi perfil, favoritos y salir.
> Create(UI-Btn and dropdown User Logged in)

- client/src/Components/User/UserLogin/UserLogin.css
- client/src/Components/User/UserLogin/UserLogin.jsx
Se crea la UI del modal con input para que el usuario recupere su contraseña en caso de olvidarla
> Create(UI-Modal Forgot pass)

- client/src/Components/AddBurger/AddBurger.css
- client/src/Components/AddBurger/AddBurger.jsx
- client/src/index.css
Refactorización de la UI de AddBurger, se realizan los siguientes cambios:
- Modificación de tipografía y color de la sección precio
- Centrado del grid en las cards de ingredientes.
- Se agregan box-shadows usando variables de la marca para homogeneizar el diseño.
- Personalización de las alerts para que combinen con la línea de diseño de la marca.
> Refactor(UI-AddBurger)

- .gitignore
- client/.env
- client/src/index.js
configuracion inicial de auth0
> config index w/auth0

- client/src/Components/User/UserRegister/UserRegister.jsx
- client/src/Redux/actions/actions.js
> local register

- client/src/Components/CardProductHome/CardProductHome.css
- client/src/Components/CardProductHome/CardProductHome.jsx
- client/src/Components/CardProductMenu/CardProductMenu.css
Se rehicieron desde cero las cards del Home ya que había conflicto con el hover
> Fix(UI hover cards)

- client/src/Components/CardCuponHome/CardCuponHome.css
- client/src/Components/CardCuponHome/CardCuponHome.jsx
- client/src/Components/Locals/Locals.jsx
- client/src/Components/Menu/Menu.css
Se corrigieron los siguientes problemas:
- Cupones de descuento, se centra la información, se mejora la imagen y se le agrega que cuando el usuario presione el botón del cupón el código se copie al portapapeles para luego poder aplicarlo en el carrito.
- Paginado se le agrega Focus para que indique en qué número de página estamos.
- Locales se editó a local ya que sólo hay uno.
> fix(UI-App)

- client/src/Components/ContactForm/ContactoForm.jsx
* Campos de texto con mensajes que indican al usuario que tipo de dato llenar
* los campos de texto se renderizan cuando el usuario no ha completado correctamente el campo del formulario
* el boton 'enviar' no funciona hasta que el usuario haya completado correctamente el formulario
> validacion del contacform

- client/src/Components/NavBar/NavBar.css
- client/src/Components/NavBar/NavBar.jsx
- client/src/Components/ShoppingCart/ShoppingCart.jsx
Se realiza sobre navBar un renderizado condicional para cuando el usuario tiene algún producto en su carrito.
> add(Cart change)

- client/src/Components/SearchBar/SearchBar.jsx
> fix (searchbar)

- client/package.json
- client/src/Components/User/UserProfileDashboard/UserProfile.css
- client/src/Components/User/UserProfileDashboard/UserProfile.jsx
Configurado cloudinary, ya se puede subir imagenes desde la dashboard de usuario.  Lo siguiente es capturar la imagen para que la tome como foto de un usuario especifico
> Configurado cloudinary

- client/src/Components/ProductDetail/ProductDetail.css
- client/src/Components/ProductDetail/ProductDetail.jsx
Se modifica la vista Product Detail:
- Se corrigió la lógica y maps que no funcionaban correctamente
- se agregan estilos 
- Completamente responsive
> fix(UI and Logic - ProductDetail)

- client/src/Components/User/UserPersonalInfo/UserPersonalInfo.jsx
- client/src/Redux/actions/actions.js
* se agrego validacion para los datos email y para que ambas contraseñas sean iguales
* se simula el hecho de despachar una accion de tipo put con los datos que quiera actualizar el usuario
* el boton de cancelar borra los datos almacenados 
* no se deja usar el boton actualizar si no hay datos
> logica de mis datos de usuario

- client/src/App.js
- client/src/Components/Admin/AdminNavBar/AdminNavBar.css
- client/src/Components/Admin/AdminNavBar/AdminNavBar.jsx
- client/src/Components/Admin/Dashboard/AdminDashboard.css
- client/src/Components/Admin/Dashboard/AdminDashboard.jsx
Se crea el panel de Admin inicial.
- Una side navbar con overlay para evitar el acumulamiento de información en una misma vista la misma se renderizará en lugar de la navbar pública de la app por medio de un condicional que verifique el rol de quién se está logueando.
- Se crea el Home básico con buttons para realizar acciones, en este caso quedará de momento funcional el de enviar newsletter con novedades.
> Create(UI admin panel)

- client/package-lock.json
- client/src/Components/ProductDetail/ProductDetail.jsx
- client/src/Components/User/UserFavorites/UserFavorites.jsx
- client/src/Components/User/UserFavoritesCard/UserFavoritesCard.jsx
- client/src/Redux/actions/actions.js
- client/src/Redux/reducer/reducer.js
- client/src/Redux/reducer/utils.js
Chicos, terminado Favoritos con localStorage incluido, hay que intentar romperlo para probarlo bien
> Favoritos con LocalStorage terminado

- client/src/Components/User/UserFavorites/UserFavorites.css
- client/src/Components/User/UserFavorites/UserFavorites.jsx
- client/src/Components/User/UserFavoritesCard/UserFavoritesCard.jsx
Refactorización del componente Favoritos UI
> Refactor(User-Favorites)

- client/src/Components/ContactForm/ContactForm.css
- client/src/Components/Menu/Menu.css
- Se refactoriza la UI de paginado para que marque correctamente en qué página está situado el usuario, también el botón se deshabilita cuando llega a la última página.
- Se refactoriza el botón del contactForm cuando está deshabilitado.
> Refactor(ContactForm y Menu paginado)

- client/src/App.js
- client/src/Components/User/UserActivateAccount/UserActivateAccount.jsx
- client/src/Components/User/UserRegister/UserRegister.jsx
> activate account

- client/src/Components/Footer/Footer.jsx
- client/src/Redux/actions/actions.js
Esta controlado el email de suscripcion del footer y con el alert solicitado, por favor revisar la conexión con el back
> Controlado el email de suscripcion del footer

- client/src/Components/User/UserLogin/UserLogin.jsx
> UserLoging.jsx

- client/src/Components/AddBurger/AddBurger.jsx
- client/src/Components/ContactForm/ContactoForm.jsx
- client/src/Components/Footer/Footer.css
- client/src/Components/Footer/Footer.jsx
- client/src/Components/User/UserLoggedIn/UserLoggedInDropdown.jsx
- client/src/Components/User/UserLogin/UserLogin.jsx
- client/src/Components/User/UserRegister/UserRegister.jsx
> Refactor(Alerts personalizadas)

- client/src/Components/CardCuponHome/CardCuponHome.css
- client/src/Components/CardCuponHome/CardCuponHome.jsx
Se Rehicieron los cupones de home, rompían al hacerse responsive
> Fix(Cupon home-responsive)

- client/src/Components/User/UserRegister/UserRegister.jsx
validaciones del registro de usuario
> userRegister validations

- client/src/Components/Menu/Menu.jsx
Reverts mabhyHs/Henrys-app#180
> Revert "old"

- api/src/controllers/users.controllers.js
- api/src/routes/users.routes.js
agregué otra ruta put en /users.
Recibe el id por params, y recibe (opcional) lastName, firstName, imgUri y passowrd por query. Verifica el token que llega por header, no verifica rol, falta validar los campos con express-validator.
Encrypta password y hace el update del repositorio.
> Update profile data

- client/public/index.html
- client/src/Components/CardProductHome/CardProductHome.css
- client/src/Components/CardProductMenu/CardProductMenu.css
- client/src/Components/CardProductMenu/CardProductMenu.jsx
- client/src/Components/NavBar/NavBar.css
- client/src/Components/NavBar/NavBar.jsx
- client/src/Components/ProductDetail/ProductDetail.css
- client/src/Components/ProductDetail/ProductDetail.jsx
- client/src/Redux/reducer/utils.js
Se realizaron las siguientes tareas:
- Se agrega al lado del carrito la cantidad de items dentro del mismo.
- Se lleva el botón de favoritos a la card en vez de en la descripción.
- Se retocaron las cards del home por un error con la imagen.
- Se personalizó la alert de utils.js.
> HotFix(Favorites, CartFill, ProductDetail)

- client/src/Components/User/UserPersonalInfo/UserPersonalInfo.jsx
- client/src/Redux/actions/actions.js
* se agrego funcionalidad a los componentes de editar datos del usuario
> Mod data user

- client/src/App.js
- client/src/Components/AddBurger/AddBurger.jsx
- client/src/Components/ShoppingCart/ShoppingCart.jsx
- client/src/Redux/actions/actions.js
- client/src/Redux/reducer/reducer.js
Modularizado MP
Agregada la ruta hacia el botón de pago
> Fede logic front

- client/src/Components/ProductDetail/ProductDetail.jsx
- client/src/Redux/actions/actions.js
- client/src/Redux/reducer/reducer.js
action y reducer para hacer clearState, y fixeado el bug de carga de cards con loading.
> fix productDetail

- api/.gitignore
- api/src/controllers/users.controllers.js
- api/src/repositories/user.repositories.js
- api/src/routes/users.routes.js
GET a /users/:id
agrego package-lock.json a .gitignore
> get user by id route

- client/src/Components/Admin/AdminNavBar/AdminNavBar.jsx
- client/src/Components/Admin/Dashboard/AdminDashboard.jsx
- client/src/Components/NavBar/NavBar.jsx
- client/src/Components/User/UserLoggedIn/UserLoggedInDropdown.css
- client/src/Components/User/UserLoggedIn/UserLoggedInDropdown.jsx
- client/src/index.css
Se realizaron los siguientes cambios:
- Se consigue por medio de renderizado condicional que en el panel del admin sólo se muestre la navBar correspondiente al mismo.
-  Al presionar Salir en la sideBar de admin se redirige hacia el Home tradicional.
- En el dropdown de cliente aparece un botón para entrar al panel en caso de tener el rol administrador.
> Modificación para que la Navbar cambie de acuerdo al rol

- client/src/Components/ShoppingCart/ShoppingCart.jsx
adicionado en el carrito de compras la opción de pedir algo antes del pago, falta lógica para conectar al back.
> Add textArea ShoppingCart

- client/src/Components/CardProductMenu/CardProductMenu.jsx
- client/src/Components/ProductsContainerMenu/ProductsContainerMenu.jsx
- client/src/Components/User/UserFavorites/UserFavorites.jsx
- client/src/Components/User/UserFavoritesCard/UserFavoritesCard.jsx
- client/src/Redux/actions/actions.js
- client/src/Redux/reducer/reducer.js
change localStore flow to DB model
> Refactor favorites

- client/src/Components/Admin/AddProduct/AddProductFilters/AddProductFilters.css
- client/src/Components/Admin/AddProduct/AddProductFilters/AddProductsFilters.jsx
- client/src/Components/Admin/AddProduct/AdminPagination/AdminPagination.jsx
- client/src/Components/Admin/AddProduct/AdminSearchBar/AdminSearchBarProduct.jsx
- client/src/Components/Admin/AddProduct/ProductCardAdmin/ProductCardAdmin.css
- client/src/Components/Admin/AddProduct/ProductCardAdmin/ProductCardAdmin.jsx
- client/src/Components/Admin/AddProduct/ProductCardAdminContainer/ProductCardAdminContainer.css
- client/src/Components/Admin/AddProduct/ProductCardAdminContainer/ProductsCardAdminContainer.jsx
- client/src/Components/Admin/AddProduct/ProductHome/AddProductHome.css
- client/src/Components/Admin/AddProduct/ProductHome/AddProductHome.jsx
Se refactoriza la UI completa del Product Home - panel admin.
> Refactor(UI-Productos Admin)

- client/src/App.js
- client/src/Components/Admin/AdminUsers/AdminUsers.css
- client/src/Components/Admin/AdminUsers/AdminUsers.jsx
Se crea la vista para gestionar usuarios desde el panel de admin:
Tabla con nombre y apellido, mail, rol y botones de accion (edita, activa o desactivar usuario)
> Create(UI-Users-Admin Panel)

- client/src/App.js
- client/src/Components/Admin/AddProduct/AddProductViews/CreateOrEditBurger/CreateOrEditBurger.css
- client/src/Components/Admin/AddProduct/AddProductViews/CreateOrEditBurger/CreateOrEditBurger.jsx
Se crea UI del componente para editar una hamburguesa desde el panel de admin
> Create(UI-Form editar hamburguesa)

- client/src/App.js
- client/src/Components/Admin/AddProduct/AddProductViews/CreateOrEditBeverage/CreateOrEditBeverage.css
- client/src/Components/Admin/AddProduct/AddProductViews/CreateOrEditBeverage/CreateOrEditBeverage.jsx
- client/src/Components/Admin/AddProduct/AddProductViews/CreateOrEditBurger/CreateOrEditBurger.jsx
- client/src/Components/Admin/AddProduct/AddProductViews/CreateOrEditCombo/CreateOrEditCombo.css
- client/src/Components/Admin/AddProduct/AddProductViews/CreateOrEditCombo/CreateOrEditCombo.jsx
Se crean las vistas de editar/crear bebidas y combos
> Create(UI- Edit beverages and combo)

- client/src/Components/User/UserReview/UserReview.css
- client/src/Components/User/UserReview/UserReview.jsx
Se refactoriza la vista para postear la review a donde el usuario va a ser redirigido desde el mail cuando realice una compra
> Refactor(UI-Reviews-post)

- client/src/Components/ReviewsContainer/DefaultReviewCard/DefaultReviewCard.jsx
- client/src/Components/ReviewsContainer/DefaultReviewCard/DefaultReviewcard.css
- client/src/Components/ReviewsContainer/ReviewCard/ReviewCard.jsx
- client/src/Components/ReviewsContainer/ReviewsContainer.css
- client/src/Components/ReviewsContainer/ReviewsContainer.jsx
Se agregó una opinion por default por si no hay opiniones por mapear. Las tarjetas de opiniones fueron rediseñadas.
> Refactorizada la seccion de reseñas

- client/src/Components/Admin/AdminUsers/AdminUsers.jsx
Se realiza la UI para cuando se presiona el botón editar en la tabla de usuarios abre un modal para poder modificar el rol.
> Create(UI-modal editar rol de usuario)

- client/src/Components/User/UserProfileDashboard/UserProfile.jsx
corregida la subida de fotos en userprofiledashboard
> se actualiza en tiempo real la imagen de usuario

- api/package.json
- api/src/controllers/mercadopago.controllers.js
- api/src/repositories/mercadopago.repositories.js
- api/src/routes/pay.routes.js
> install axios, add GET /pay/mercadopago/:id

- client/src/Components/Admin/AdminUsers/AdminUsers.jsx
* se implemento el cambio de rol funcional
*mensaje de confirmacion de cambio exitoso
* se implemento paginacion
* filtros funcionales por rol (falta activos y desactivos) cada uno con paginacion
*se renderiza los botones correctos si un usuario esta desactivo o no
> Funcionalidades al 80%

- client/src/Components/Admin/AdminUsers/AdminUsers.jsx
Funcionalidad completa de los usuarios en el panel de admin
* se puede cambiar el rol de los usuarios
* se puede desactivar y activar a los usuarios
* se puede hacer filtrados por rol o por estado de activos a la vista de los usuarios
* tiene paginado tanto como en la vista de todos los usuarios como en cada filtro
> Users admin activos e inactivos

- client/src/Components/User/UserReview/UserReview.jsx
- client/src/Redux/actions/actions.js
Ya se puede postear opiniones, se captura correctamente el autor y la id del usuario. Todavia resta controlar bien el formulario; no se esta manejando bien el estado por lo que el form tiene comportamientos inesperados (los inputs quedan desactualizados por un caracter); durante el domingo lo corrijo; de igual manera voy guardando el trabajo.
> conexion con back. comportamientos inesperados

- client/src/Components/CardProductHome/CardProductHome.jsx
- client/src/Components/CuponContainerHome/CuponContainerHome.css
- client/src/Components/CuponContainerHome/CuponContainerHome.jsx
Se refactoriza la sección de cupones del home, para que quede mejor visualmente, se delimite donde comienza y donde termina.
> Refactor(Cupons section)

- client/src/Components/Home/Home.jsx
- client/src/Components/NavBar/NavBar.jsx
- client/src/Components/ReviewsContainer/DefaultReviewCard/DefaultReviewcard.css
- client/src/Components/ReviewsContainer/ReviewCard/ReviewCard.css
- client/src/Components/ReviewsContainer/ReviewsContainer.jsx
Se refactoriza la sección de review, se agrega un link en la navbar que te redirecciona para poder ver el contenedor de las mismas, se ajustan las sombras utilizando las variables establecidas en el index.css
> Refactor(UI- reviews)

- client/src/Components/Admin/AddProduct/AddProductViews/CreateOrEditCombo/CreateOrEditCombo.jsx
Fede, los select están  funcionando bastante bien. Hay un handleSlect y un handleDelete por cada select.
Faltaría arreglar imgUri.
> chenge selects

- client/src/Components/User/UserReview/UserReview.css
- client/src/Components/User/UserReview/UserReview.jsx
El formulario para enviar opiniones ya se comporta de manera predecible. Se aplicó en el front las mismas validaciones que realiza el back.
> control de errores y estilos de error userReview

- client/src/Components/NavBar/NavBar.jsx
- client/src/Components/employeePanel/employeeHome/EmployeeHome.jsx
Se realiza logica para conseguir que cuando el empleado ingresa al panel del mismo se modifique la navbar.
> Switch navbar cuando se entra al panel de empleado

- client/src/Components/Home/Home.jsx
- client/src/Components/User/UserLoggedIn/UserLoggedInDropdown.jsx
Se realiza la lógica para que al detectar que quién se loguea es empleado aparezca el botón de empleado que lleva al home del mismo.
> switchDropdownBtn

- api/src/middlewares/beverageValidation.js
- api/src/middlewares/burgerValidation.js
- api/src/middlewares/comboValidation.js
- api/src/middlewares/friesValidation.js
- api/src/models/Beverage.js
- api/src/models/Burger.js
- api/src/models/BurgerBase.js
- api/src/models/Combo.js
- api/src/models/Fries.js
> Refactor img uri models and validator

- client/src/Components/ShoppingCart/ShoppingCart.css
- client/src/Components/ShoppingCart/ShoppingCart.jsx
Se refactoriza el renderizado condicional cuando el carrito se encuentra vacio para que sea coherente con la linea de diseño
> Refactor(render msj when cart is empty)

- client/src/Components/User/UserFavorites/UserFavorites.css
- client/src/Components/User/UserFavorites/UserFavorites.jsx
Se agrega renderizado condicional para cuando los favoritos se encuentran vacíos.
> refactor(add text when is empty)

- client/src/Components/ShoppingCart/ShoppingCart.css
- client/src/Components/ShoppingCart/ShoppingCart.jsx
Se refactoriza la vista previa al pago del carrito, se le da estilo a la sección de descuento y textarea, todo completamente responsive.
> Refactor(ShoppingCartView)

- api/src/repositories/order.repositories.js
> Add html to nodemailer send qr

- client/src/Components/Admin/AdminUsers/AdminUsers.css
- client/src/Components/Admin/AdminUsers/AdminUsers.jsx
Se realiza el estilado del paginado de la sección usuarios del paner de Admin
> Refactor(pagination styled)

- client/src/Components/Admin/Coupons/CouponAdmin/CouponAdmin.css
- client/src/Components/Admin/Coupons/CouponAdmin/CouponAdmin.jsx
- client/src/Components/Admin/Coupons/CouponUpdate/CouponUpdate.css
- client/src/Components/Admin/Coupons/CouponUpdate/CouponUpdate.jsx
queda un pequeño margen en esos anchos pero nada mas
> resta resposivizar entre 370 y 360px

- client/src/Components/ContactForm/ContactForm.css
- client/src/Components/ContactForm/ContactoForm.jsx
- client/src/Components/Menu/Menu.css
- client/src/Components/Pagination/Pagination.module.css
- client/src/Components/ReviewsContainer/DefaultReviewCard/DefaultReviewCard.jsx
- client/src/Components/ReviewsContainer/DefaultReviewCard/DefaultReviewcard.css
- client/src/Components/ReviewsContainer/ReviewCard/ReviewCard.css
- client/src/Components/ReviewsContainer/ReviewCard/ReviewCard.jsx
- client/src/Components/ShoppingCart/ShoppingCart.css
- client/src/Components/ShoppingCart/ShoppingCart.jsx
- client/src/Components/User/UserRegister/UserRegister.css
- client/src/Components/User/UserRegister/UserRegister.jsx
- Se arregla el form de registro donde los errores salían incorrectamente posicionados ya que se habían copiado literalmente los mismos de los errores del formulario de contacto, por ésta razón no funcionaban correctamente porque no se adaptaron cuando se implementó la validación.
- Se arregla el form de contacto para que los errores sean mas descriptivos
- Se hizo ajuste de las cards de reviews ya que no seguían la linea de diseño del sitio.
- Se corrige el diseño de la paginación para que quede homogeneo con el estilo del sitio.
- Se arregla el componente cuando el carrito está vacio(no tenía min-height y rompía).
> UI hot fix

- client/src/App.js
- client/src/Components/Admin/AddProduct/AddProductFilters/AddProductsFilters.jsx
- client/src/Components/Admin/AddProduct/AddProductViews/CreateOrEditIngredients/CreateOrEditIngredients.css
- client/src/Components/Admin/AddProduct/AddProductViews/CreateOrEditIngredients/CreateOrEditIngredients.jsx
Se realiza la UI del formulario para creación/edición de los ingredientes en el panel de administrador.
> Create(Ingredients form create/edit)

- client/src/Components/Admin/AddProduct/AdminPagination/AdminPagination.css
- client/src/Components/Admin/AddProduct/AdminPagination/AdminPagination.jsx
- client/src/Components/Admin/AddProduct/ProductCardAdmin/ProductCardAdmin.css
- client/src/Components/Admin/AddProduct/ProductCardAdmin/ProductCardAdmin.jsx
Refctorización de la sección home del panel de admin, se estilan los botones, se estila el paginado para que quede acorde al diseño, todo responsive.
> Refactor(UI-pagination and card product btn)

- client/src/Components/Admin/AddProduct/EditProducts/EditProducts.jsx
- client/src/Components/Admin/AddProduct/ProductHome/AddProductHome.jsx
- client/src/Components/Loading/Loading.module.css
- client/src/Redux/actions/actions.js
- Se agrega loading cuando se edita un producto en admin.
- se agrega no se encuentran resultados en searchabar
> Fix(Loading and searchbar)

- client/src/Components/employeePanel/EmployeeNavBar/EmployeeNavBar.css
- client/src/Components/employeePanel/EmployeeNavBar/EmployeeNavBar.jsx
- client/src/Components/employeePanel/employeeHome/EmployeeHome.jsx
> refactor(navbar links)

- client/src/Components/Admin/AddProduct/AddProductViews/CreateOrEditIngredients/CreateOrEditIngredients.jsx
Se refactoriza el form de editar/crear ingrediente, se le agrega imagen
> Refactor(create or edit ingredients)

- client/src/Components/employeePanel/EmployeeOrderReady/EmployeeOrderReady.jsx
- client/src/Components/employeePanel/EmployeePendignOrder/EmployeePendingOrder.css
- client/src/Components/employeePanel/EmployeePendignOrder/EmployeePendingOrder.jsx
Se agrega renderizado condicional para cuando no hay más ordenes pendientes ó listas
> Refactor( orders pending and reaady empty )

- client/src/Components/NotFound/NotFound.module.css
Se corrige el min-height del componente 404
> fix(min-height 404)

- api/src/models/Ingredient.js
- api/src/repositories/burgerBase.repositories.js
- api/src/repositories/ingredient.repositories.js
> refactor querys
